services:
  - type: web
    name: terranova-composer-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_STORE
        value: terranova-og.myshopify.com
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: APP_URL
        sync: false
